version: '2'
services:
  #  db:
  #    image: postgres
  #    restart: always
  #    env_file: .env
  #    expose:
  #      - "5432"
  #    ports:
  #      - "5432:5432"
  api:
    build:
      context: .
    volumes:
      - .:/api
    env_file: .env
    expose:
      - "8000"
    ports:
      - "80:8000"
    # links:
      #  - "db:database"
